name: Test Workflow

on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Powerpipe
      uses: ./ # This points to your local action
      with:
        powerpipe-version: '0.1.2'

    - name: Verify Powerpipe Installation
      run: |
        powerpipe -v
